on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'infra/**'
            - 'src/**'
            - '.github/**'

# GitHub Actions workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config`

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            # AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install azd
              uses: Azure/setup-azd@v2

            - name: Install Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install Azure Function Core Tools
              run: |
                  sudo apt-get update
                  sudo apt-get install azure-functions-core-tools-4

            - name: Log in with Azure (Federated Credentials)
              if: ${{ env.AZURE_CLIENT_ID != '' }}
              run: |
                  azd auth login `
                    --client-id "$Env:AZURE_CLIENT_ID" `
                    --federated-credential-provider "github" `
                    --tenant-id "$Env:AZURE_TENANT_ID"
              shell: pwsh

            - name: Provision Infrastructure
              run: azd provision --no-prompt
              env:
                  AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
                  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
                  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
                  AZURE_KEY_VAULT_NAME: ${{ vars.AZURE_KEY_VAULT_NAME }}

            - name: Deploy Application
              run: azd deploy web --no-prompt #deploy api fails for some reason - investigating
              env:
                  AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
                  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
                  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
